// Generated by gencpp from file webcam_snapshot/take_snapshotRequest.msg
// DO NOT EDIT!


#ifndef WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOTREQUEST_H
#define WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webcam_snapshot
{
template <class ContainerAllocator>
struct take_snapshotRequest_
{
  typedef take_snapshotRequest_<ContainerAllocator> Type;

  take_snapshotRequest_()
    {
    }
  take_snapshotRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct take_snapshotRequest_

typedef ::webcam_snapshot::take_snapshotRequest_<std::allocator<void> > take_snapshotRequest;

typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotRequest > take_snapshotRequestPtr;
typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotRequest const> take_snapshotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webcam_snapshot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webcam_snapshot/take_snapshotRequest";
  }

  static const char* value(const ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct take_snapshotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::webcam_snapshot::take_snapshotRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOTREQUEST_H
