// Generated by gencpp from file webcam_snapshot/take_snapshot.msg
// DO NOT EDIT!


#ifndef WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOT_H
#define WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOT_H

#include <ros/service_traits.h>


#include <webcam_snapshot/take_snapshotRequest.h>
#include <webcam_snapshot/take_snapshotResponse.h>


namespace webcam_snapshot
{

struct take_snapshot
{

typedef take_snapshotRequest Request;
typedef take_snapshotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct take_snapshot
} // namespace webcam_snapshot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webcam_snapshot::take_snapshot > {
  static const char* value()
  {
    return "5fdcda0f95399f6b72fea1643acc7e4b";
  }

  static const char* value(const ::webcam_snapshot::take_snapshot&) { return value(); }
};

template<>
struct DataType< ::webcam_snapshot::take_snapshot > {
  static const char* value()
  {
    return "webcam_snapshot/take_snapshot";
  }

  static const char* value(const ::webcam_snapshot::take_snapshot&) { return value(); }
};


// service_traits::MD5Sum< ::webcam_snapshot::take_snapshotRequest> should match 
// service_traits::MD5Sum< ::webcam_snapshot::take_snapshot > 
template<>
struct MD5Sum< ::webcam_snapshot::take_snapshotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webcam_snapshot::take_snapshot >::value();
  }
  static const char* value(const ::webcam_snapshot::take_snapshotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webcam_snapshot::take_snapshotRequest> should match 
// service_traits::DataType< ::webcam_snapshot::take_snapshot > 
template<>
struct DataType< ::webcam_snapshot::take_snapshotRequest>
{
  static const char* value()
  {
    return DataType< ::webcam_snapshot::take_snapshot >::value();
  }
  static const char* value(const ::webcam_snapshot::take_snapshotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webcam_snapshot::take_snapshotResponse> should match 
// service_traits::MD5Sum< ::webcam_snapshot::take_snapshot > 
template<>
struct MD5Sum< ::webcam_snapshot::take_snapshotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webcam_snapshot::take_snapshot >::value();
  }
  static const char* value(const ::webcam_snapshot::take_snapshotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webcam_snapshot::take_snapshotResponse> should match 
// service_traits::DataType< ::webcam_snapshot::take_snapshot > 
template<>
struct DataType< ::webcam_snapshot::take_snapshotResponse>
{
  static const char* value()
  {
    return DataType< ::webcam_snapshot::take_snapshot >::value();
  }
  static const char* value(const ::webcam_snapshot::take_snapshotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOT_H
