// Generated by gencpp from file webcam_snapshot/take_snapshotResponse.msg
// DO NOT EDIT!


#ifndef WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOTRESPONSE_H
#define WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webcam_snapshot
{
template <class ContainerAllocator>
struct take_snapshotResponse_
{
  typedef take_snapshotResponse_<ContainerAllocator> Type;

  take_snapshotResponse_()
    : confirmation()  {
    }
  take_snapshotResponse_(const ContainerAllocator& _alloc)
    : confirmation(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _confirmation_type;
  _confirmation_type confirmation;





  typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct take_snapshotResponse_

typedef ::webcam_snapshot::take_snapshotResponse_<std::allocator<void> > take_snapshotResponse;

typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotResponse > take_snapshotResponsePtr;
typedef boost::shared_ptr< ::webcam_snapshot::take_snapshotResponse const> take_snapshotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webcam_snapshot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fdcda0f95399f6b72fea1643acc7e4b";
  }

  static const char* value(const ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fdcda0f95399f6bULL;
  static const uint64_t static_value2 = 0x72fea1643acc7e4bULL;
};

template<class ContainerAllocator>
struct DataType< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webcam_snapshot/take_snapshotResponse";
  }

  static const char* value(const ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string confirmation\n\
\n\
";
  }

  static const char* value(const ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirmation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct take_snapshotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webcam_snapshot::take_snapshotResponse_<ContainerAllocator>& v)
  {
    s << indent << "confirmation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.confirmation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBCAM_SNAPSHOT_MESSAGE_TAKE_SNAPSHOTRESPONSE_H
